apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: "cluster-store"
  namespace: {{ .Values.cluster.applicationsNamespace }}
spec:
  provider:
    vault:
      server: {{ .Values.vault.serverAddress | quote }}
      path: {{ .Values.vault.kvEngine | quote }}
      version: "v2"
      auth:
        tokenSecretRef:
          name: {{ .Values.vault.tokenSecret | quote }}
          key: "token"
---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: "common-store"
  namespace: {{ .Values.cluster.applicationsNamespace }}
spec:
  provider:
    vault:
      server: {{ .Values.vault.serverAddress | quote }}
      path: "common"
      version: "v2"
      auth:
        tokenSecretRef:
          name: {{ .Values.vault.tokenSecret | quote }}
          key: "token"
