apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: "cluster-store"
spec:
  provider:
    vault:
      server: {{ .Values.vault.serverAddress | quote }}
      namespace: {{ .Values.vault.namespace | quote }}
      path: {{ .Values.vault.kvEngine | quote }}
      version: "v2"
      auth:
        jwt:
          path: "jwt-{{ .Values.vault.mountPath }}"
          role: {{ .Values.vault.accountRole }}
          kubernetesServiceAccountToken:
            serviceAccountRef:
              name: {{ index .Values "external-secrets" "serviceAccount" "name" }}
              namespace: {{ .Release.Namespace }}
            audiences:
            - vault
            expirationSeconds: 600
---
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: "common-store"
spec:
  provider:
    vault:
      server: {{ .Values.vault.serverAddress | quote }}
      namespace: {{ .Values.vault.namespace | quote }}
      path: "common"
      version: "v2"
      auth:
        jwt:
          path: "jwt-{{ .Values.vault.mountPath }}"
          role: {{ .Values.vault.accountRole }}
          kubernetesServiceAccountToken:
            serviceAccountRef:
              name: {{ index .Values "external-secrets" "serviceAccount" "name" }}
              namespace: {{ .Release.Namespace }}
            audiences:
            - vault
            expirationSeconds: 600